### ISSUE TITLE
Variables: undefined

### ISSUE THREAD

**Issue by tsvetann** [Hemann55/medusa-plugin-mailjet#3]
When I test a new user creation first I get: info:    Processing customer.created which has 0 subscribers

But it seems to actually trigger the mailjet plugin which however gives me: Variables: undefined. How do I get the first and last name?

**Comment by tsvetann** [comment]
I think you have a bug here:

`nonNull = Object.keys(dynamic_template_data).forEach(function (key) {
                  if (dynamic_template_data[key] === null) {
                    delete dynamic_template_data[key];
                  }
                });`

forEach always returns undefined. Please refer to the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach):

**Comment by Hemann55** [comment]
Fixed it. Let me know if it works for you

**Comment by tsvetann** [comment]
Now after upgrading I get the following: Processing customer.created which has 0 subscribers

**Comment by Hemann55** [comment]
Are variables (first and last names) being sent correctly?

**Comment by tsvetann** [comment]
It is. thanks for fixing it
