### ISSUE TITLE
support invite.create

### ISSUE THREAD

**Issue by tsvetann** [Hemann55/medusa-plugin-mailjet#4]
Do you plan on supporting the invite.create event? This is emitted when a user is invited to become an admin user?

**Comment by Hemann55** [comment]
Added support for invite.created

`token` and invite `id` is passed as variables. You'll have to format the invite link in Mailjet Template according to your admin url which may look something like this -
http://localhost:7000/invite?token={{var:token}}

Please refer to this [thread](https://discord.com/channels/876835651130097704/1062609605315809340/1062743456365158461) for more info.
