### ISSUE TITLE
Prevent account registration email from being sent to guest users upon order creation

### ISSUE THREAD

**Issue by tsvetann** [Hemann55/medusa-plugin-mailjet#6]
### Description:

I've noticed a problem with the customer.create event that triggers an account registration email. Specifically, when a user with the email test@test.com places an order as a guest, they receive an account registration email, even though they have not created an account. This becomes problematic when the same user decides to create an account at a later time (using the same email), as they will receive the same account registration email again, leading to a suboptimal user experience.

### Steps to reproduce:

1. As a guest user with email test@test.com, create an order.
2. Observe that an account registration email is sent to test@test.com.
3. As test@test.com, create a new account.
4. Observe that the same account registration email is sent to test@test.com again.

### Expected behavior:

The account registration email should only be triggered when customer.has_account is true. In the steps above, the email should not be sent at step 2, but should be sent at step 4.

### Suggested solution:

Modify the event trigger conditions for sending the account registration email to include a check for customer.has_account being true.

Please let me know if any additional information is required. Thank you!

**Comment by tsvetann** [comment]
@Hemann55 I understand that you might very busy. I'm actively using your plugin and I can give you a hand helping maintain this nice plugin. Are you willing to add me as a maintainer? Thanks

**Comment by Hemann55** [comment]
Hi @tsvetann ...Sorry for the delay. Have added you as collaborator. Please accept the invite

Thank you for understanding :)
